export interface GraphicAsset {
  id: string
  name: string
  type: 'illustration' | 'icon' | 'photo' | 'logo'
  width: number
  height: number
  size: string
  gradient: [string, string]
  tags: string[]
  createdAt: string
}

export const mockAssets: GraphicAsset[] = [
  {
    id: 'asset-1',
    name: 'Hero Illustration',
    type: 'illustration',
    width: 1920,
    height: 1080,
    size: '2.4 MB',
    gradient: ['var(--color-warning)', '#D97706'],
    tags: ['hero', 'landing', 'gradient'],
    createdAt: '2026-03-28T10:00:00Z',
  },
  {
    id: 'asset-2',
    name: 'Dashboard Icon Set',
    type: 'icon',
    width: 24,
    height: 24,
    size: '12 KB',
    gradient: ['var(--accent)', 'var(--accent)'],
    tags: ['icons', 'dashboard', 'ui'],
    createdAt: '2026-03-27T14:30:00Z',
  },
  {
    id: 'asset-3',
    name: 'Team Photo',
    type: 'photo',
    width: 4000,
    height: 2667,
    size: '5.1 MB',
    gradient: ['var(--color-success)', 'var(--color-success)'],
    tags: ['team', 'people', 'about'],
    createdAt: '2026-03-26T09:15:00Z',
  },
  {
    id: 'asset-4',
    name: 'Product Logo',
    type: 'logo',
    width: 512,
    height: 512,
    size: '48 KB',
    gradient: ['var(--accent)', '#DB2777'],
    tags: ['logo', 'brand', 'primary'],
    createdAt: '2026-03-25T16:45:00Z',
  },
  {
    id: 'asset-5',
    name: 'Onboarding Flow',
    type: 'illustration',
    width: 1440,
    height: 900,
    size: '1.8 MB',
    gradient: ['var(--accent)', 'var(--accent)'],
    tags: ['onboarding', 'flow', 'steps'],
    createdAt: '2026-03-24T11:20:00Z',
  },
  {
    id: 'asset-6',
    name: 'Settings Gear',
    type: 'icon',
    width: 32,
    height: 32,
    size: '8 KB',
    gradient: ['var(--text-tertiary)', 'var(--text-tertiary)'],
    tags: ['settings', 'gear', 'cog'],
    createdAt: '2026-03-23T13:00:00Z',
  },
  {
    id: 'asset-7',
    name: 'Office Interior',
    type: 'photo',
    width: 3840,
    height: 2160,
    size: '4.7 MB',
    gradient: ['var(--color-warning)', '#EA580C'],
    tags: ['office', 'workspace', 'interior'],
    createdAt: '2026-03-22T08:30:00Z',
  },
  {
    id: 'asset-8',
    name: 'Favicon',
    type: 'logo',
    width: 32,
    height: 32,
    size: '4 KB',
    gradient: ['var(--color-error)', 'var(--color-error)'],
    tags: ['favicon', 'brand', 'small'],
    createdAt: '2026-03-21T17:10:00Z',
  },
  {
    id: 'asset-9',
    name: 'Feature Spotlight',
    type: 'illustration',
    width: 800,
    height: 600,
    size: '980 KB',
    gradient: ['var(--accent)', '#0891B2'],
    tags: ['feature', 'spotlight', 'marketing'],
    createdAt: '2026-03-20T12:00:00Z',
  },
  {
    id: 'asset-10',
    name: 'Arrow Icons Pack',
    type: 'icon',
    width: 24,
    height: 24,
    size: '16 KB',
    gradient: ['#A855F7', '#9333EA'],
    tags: ['arrows', 'navigation', 'ui'],
    createdAt: '2026-03-19T15:45:00Z',
  },
  {
    id: 'asset-11',
    name: 'Product Shot',
    type: 'photo',
    width: 2400,
    height: 1600,
    size: '3.2 MB',
    gradient: ['var(--accent)', '#0D9488'],
    tags: ['product', 'mockup', 'device'],
    createdAt: '2026-03-18T10:30:00Z',
  },
  {
    id: 'asset-12',
    name: 'Wordmark Logo',
    type: 'logo',
    width: 800,
    height: 200,
    size: '24 KB',
    gradient: ['var(--color-error)', '#E11D48'],
    tags: ['wordmark', 'brand', 'text'],
    createdAt: '2026-03-17T09:00:00Z',
  },
]
