export type NotificationType = 'comment' | 'task' | 'approval' | 'mention' | 'system'

export interface Notification {
  id: string
  type: NotificationType
  actor: { name: string; avatar: string }
  action: string
  target: string
  timestamp: string
  read: boolean
  message: string
}

export const mockNotifications: Notification[] = [
  {
    id: 'n-1',
    type: 'comment',
    actor: { name: 'Alice Chen', avatar: 'AC' },
    action: 'commented on',
    target: 'Dashboard Component',
    timestamp: '2026-03-29T09:30:00Z',
    read: false,
    message: 'The spacing on the sidebar looks off on tablet screens. Can we adjust the breakpoint to 1024px?',
  },
  {
    id: 'n-2',
    type: 'approval',
    actor: { name: 'Bob Martinez', avatar: 'BM' },
    action: 'requested approval for',
    target: 'Brand Palette v2',
    timestamp: '2026-03-29T09:15:00Z',
    read: false,
    message: 'Updated the primary colors and gradient system. Please review the new palette before we push to production.',
  },
  {
    id: 'n-3',
    type: 'mention',
    actor: { name: 'Carol Wang', avatar: 'CW' },
    action: 'mentioned you in',
    target: 'Feature: User Auth discussion',
    timestamp: '2026-03-29T08:45:00Z',
    read: false,
    message: '@you What do you think about using passkeys instead of traditional passwords for the MVP launch?',
  },
  {
    id: 'n-4',
    type: 'task',
    actor: { name: 'David Kim', avatar: 'DK' },
    action: 'assigned you to',
    target: 'Implement login flow',
    timestamp: '2026-03-29T08:00:00Z',
    read: true,
    message: 'Please implement the login flow with social providers (Google, GitHub). Use the auth-service package.',
  },
  {
    id: 'n-5',
    type: 'system',
    actor: { name: 'System', avatar: 'SY' },
    action: 'deployed',
    target: 'Release v2.0',
    timestamp: '2026-03-29T07:30:00Z',
    read: true,
    message: 'New release v2.0 has been deployed to production. All health checks passed.',
  },
  {
    id: 'n-6',
    type: 'comment',
    actor: { name: 'Eve Park', avatar: 'EP' },
    action: 'replied to your comment on',
    target: 'Navigation Redesign',
    timestamp: '2026-03-28T16:20:00Z',
    read: false,
    message: 'Great point about the mobile menu. I\'ll update the wireframes to include the bottom sheet pattern.',
  },
  {
    id: 'n-7',
    type: 'approval',
    actor: { name: 'Frank Liu', avatar: 'FL' },
    action: 'approved',
    target: 'Typography System PR',
    timestamp: '2026-03-28T15:00:00Z',
    read: true,
    message: 'Looks great! The Inter font pairing with the display weights works really well.',
  },
  {
    id: 'n-8',
    type: 'task',
    actor: { name: 'Grace Yoon', avatar: 'GY' },
    action: 'completed',
    target: 'Setup CI/CD Pipeline',
    timestamp: '2026-03-28T14:30:00Z',
    read: true,
    message: 'CI/CD pipeline is now configured with GitHub Actions. Build times are under 3 minutes.',
  },
  {
    id: 'n-9',
    type: 'mention',
    actor: { name: 'Henry Zhao', avatar: 'HZ' },
    action: 'mentioned you in',
    target: 'Canvas Studio brainstorm',
    timestamp: '2026-03-28T11:00:00Z',
    read: false,
    message: '@you Can you review the infinite canvas POC? I think the SVG approach has better performance than canvas API.',
  },
  {
    id: 'n-10',
    type: 'system',
    actor: { name: 'System', avatar: 'SY' },
    action: 'detected an issue with',
    target: 'API Response Times',
    timestamp: '2026-03-27T18:00:00Z',
    read: true,
    message: 'Average response time for /api/tasks exceeded 500ms threshold. Investigating database query performance.',
  },
  {
    id: 'n-11',
    type: 'comment',
    actor: { name: 'Iris Novak', avatar: 'IN' },
    action: 'commented on',
    target: 'Workflow Automation Rules',
    timestamp: '2026-03-27T10:30:00Z',
    read: true,
    message: 'The trigger conditions need better documentation. Can we add inline help text for each rule type?',
  },
  {
    id: 'n-12',
    type: 'task',
    actor: { name: 'Jack Porter', avatar: 'JP' },
    action: 'changed priority of',
    target: 'Implement dark mode toggle',
    timestamp: '2026-03-26T16:00:00Z',
    read: true,
    message: 'Moved to high priority per stakeholder feedback. Users are requesting this frequently.',
  },
  {
    id: 'n-13',
    type: 'approval',
    actor: { name: 'Karen Singh', avatar: 'KS' },
    action: 'requested changes on',
    target: 'Landing Page Copy',
    timestamp: '2026-03-26T12:00:00Z',
    read: true,
    message: 'The hero headline needs to be more action-oriented. See my inline comments for specific suggestions.',
  },
  {
    id: 'n-14',
    type: 'mention',
    actor: { name: 'Leo Tanaka', avatar: 'LT' },
    action: 'mentioned you in',
    target: 'Sprint Retro Notes',
    timestamp: '2026-03-25T17:00:00Z',
    read: true,
    message: '@you Your point about improving code review turnaround time was noted as a top action item.',
  },
  {
    id: 'n-15',
    type: 'system',
    actor: { name: 'System', avatar: 'SY' },
    action: 'completed backup for',
    target: 'Production Database',
    timestamp: '2026-03-25T03:00:00Z',
    read: true,
    message: 'Weekly backup completed successfully. Backup size: 2.4 GB. Retention policy: 30 days.',
  },
]
